version: '2'

services:
  db:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: ticker_db
    ports:
      - "3306:3306"
    tty: true
  app:
    build: .
    restart: always
    container_name: ticker_app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
